tap "tilt-dev/tap"

brew "chamber"
brew "gnupg"
brew "git"
brew "git-crypt"
brew "gnu-getopt"
brew "readline"
brew "jq"
brew "make"
brew "pass"
brew "pass-otp"
brew "powerline-go"
brew "rsync"
brew "socat"
brew "tmux"
brew "vim"
brew "gh"
brew "screen"
brew "sops"
brew "stern"
brew "yubico-piv-tool"
brew "bat"
brew "git-delta"
brew "gron"
brew "step"
brew "direnv"
brew "rg"
brew "tilt"

if OS.mac?
  tap "homebrew/cask"
  tap "homebrew/cask-fonts"
  tap "cloudflare/cloudflare"
  tap "aws/tap"

  cask "aws-vault"
  cask "1password"
  cask "keeper-password-manager"
  cask "chromedriver"
  cask "docker"
  cask "google-chrome"
  cask "iterm2"
  cask "skitch"
  cask "superduper"
  cask "session-manager-plugin"
  cask "postman"
  cask "font-juliamono"
  cask "jetbrains-toolbox"
  cask "oracle-jdk"
  cask "balenaetcher"
  cask "tunnelblick"
  cask "lens"
  cask "divvy"
  cask "snagit"
  cask "dbeaver-community"

  brew "htop"
  brew "pinentry-mac"
  brew "terminal-notifier"
  brew "awscli"
else
  brew "aws-vault"
end
