repo: https://github.com/amanibhavam/homedir
revision: master
version: master
variant: ""

base_dockerfile: Dockerfile.base
base_source: "python:3.10"
base_destination: "k3d-hub.defn.ooo:5000/amanibhavam/homedir:base"

brew_dockerfile: Dockerfile.brew
brew_source: "k3d-hub.defn.ooo:5000/amanibhavam/homedir:base"
brew_destination: "k3d-hub.defn.ooo:5000/amanibhavam/homedir:brew"

home_dockerfile: Dockerfile.home
home_source: "k3d-hub.defn.ooo:5000/amanibhavam/homedir:brew"
home_destination: "k3d-hub.defn.ooo:5000/amanibhavam/homedir:home"
